### ISSUE TITLE
How to change display format

### ISSUE THREAD

**Issue by EgorKorol** [mainawycliffe/Custom-Date-Format-using-Material-DatePicker#1]
Hi! Help me please. How to change display value format? (display: `Feb 2012` in input, which depended at format @Input())

**Comment by mainawycliffe** [comment]
Hi, you need to pass the following format: `format="MMM YYYY"`, so you controls looks like this in the examples given:

```html
<div fxFlex="100" fxLayout="column" style="margin: 20px;">
   <app-date-picker placeholder="Enter The Fifth Date" [(ngModel)]="sixthDate" format="MMM YYYY"></app-date-picker>
 <span> Date Format:
   <strong>YY/MM/DD</strong> - Value:
   <strong> {{ sixthDate }}</strong>
 </span>
</div>
```

Here are all the formats you can use: https://momentjs.com/docs/#/parsing/string-formats/

**Comment by EgorKorol** [comment]
It doesn't work for me.. In your demo you use different format value, but display DD/MM/YYYY.
Value in `ngModel` or `formControl` really formatted, but display the same(DD/MM/YYYY).
Can you help me in this question?

**Comment by mainawycliffe** [comment]
Can you share a screen shot, on my side, it is working as expected. I have even deployed it on production using formControl (Reactive Forms) instead of ngModel (Template Driven Forms)

**Comment by EgorKorol** [comment]
[ScreenShot](https://user-images.githubusercontent.com/26375755/51830001-de1da380-22ff-11e9-8e8c-af42196bce4c.png)

```<app-date-picker placeholder="Enter The First Date" formControlName="bDate" format="MMM YYYY"></app-date-picker>```

**Comment by mainawycliffe** [comment]
Okay, can you explain what you are trying to do please. Because, i understood your question correctly, you wanted to use the following form: `Feb 2019` and it is working as expected from your example, unless i misunderstood your question.

**Comment by EgorKorol** [comment]
[Your demo](https://angular-material-date-picker.s3-us-west-2.amazonaws.com/index.html)

![What's I want to display](https://user-images.githubusercontent.com/26375755/51830821-cba46980-2301-11e9-9f8b-1e4603005f97.png)

**Comment by mainawycliffe** [comment]
For that, you would need to change the Material Date Picker Format itself, my approach was to give maximum flexibility, allowing you to use multiple date formats in one form even on the same form. https://material.angular.io/components/datepicker/examples

I didn't foresee somewhere where one would need to change the way the date is shown to the user, but rather how the date is process on backend based on an API requirement

**Comment by EgorKorol** [comment]
Ooh, got it. I thought your implementation would eliminate this :(
Thank you very much for your time!

**Comment by mainawycliffe** [comment]
One approach i can think of is hiding the date-picker input and having another form-field in its place display the date in the format you want. That can be a nice workaround.

**Comment by EgorKorol** [comment]
Hmm, I think that will do for me. Thanks again for the help!

**Comment by mainawycliffe** [comment]
Hi, i have been working on your specific problem, and i believe the best way of achieving your approach of changing the display value is to use Dependency injection on a single component that wraps around the material date picker. This way, it only affects one date picker and not all other date pickers in your app. So, i went ahead and created a second component on this [repo](https://github.com/mainawycliffe/Custom-Date-Format-using-Material-DatePicker/tree/master/src/app/utility/date-picker2), with everything you need. You can modify the formats [here](https://github.com/mainawycliffe/Custom-Date-Format-using-Material-DatePicker/blob/a1ed8b781cd7c35cf7cac42664ad638205bb2c47/src/app/utility/date-picker2/date-picker2.component.ts#L22)
